### PR TITLE
fixed parsing error when input broken comments

### PR DESCRIPTION
**Pull request by rhiokim**
String.prototyp.charAt do not return Null.
Return char(String) or empty string ""

```
var css = require('css');
css.parse('/* comments'); // While loop can not stop
```

### CODE REVIEW

**Comment by jonathanong** [comment]
can you add a test?

**Comment by rhiokim** [comment]
@jonathanong yep! sure :-)

**Comment by jonathanong** [comment]
will you be adding a test?

**Comment by jonathanKingston** [comment]
@rhiokim I only noticed this after I was ready to push the fix... I wasn't trying to step on your toes at all. Thanks for all the great work guys.

**Pull request closed without merging**
