### PR TITLE
Remove comments from properties and values in parse time.

### PR DESCRIPTION
**Pull request by vladkens**
Fix bug in issue #48. Now parser removes from properties and values comments, but doing it directly in this fields, for this reason parser has trues info about lineno and column for error messages.

### CODE REVIEW

**Comment by jonathanong** [comment]
i don't mind merging this since i think doing this is pretty silly anyways, but are people going to be annoying with this? there are some people who want the CSS to be exact, including spacing.

**Comment by tj** [comment]
some hacks require madness like this but whether or not they are relevant anymore who knows, I stay away from that stuff haha

**Comment by matanox** [comment]
As much as I understand this bug and pull request, isn't it better removing all comments throughout (including comments outside properties and values) before unleashing the parser? Are comments gracefully handled when appearing outside properties and values? _sorry, I haven't checked_.

That would be just two lines of code and one pass over the entire input string for removing all comments from the whole input string (as much as javascript's `replace` function is efficient). Something like:

``` coffeescript
  # Regex replace: remove all CSS comments (of the form /* anything */) 
  # First back-slash escapes the string, not the regex
  regex = new RegExp('/\\*.*?\\*/', 'g') 
  string = string.replace(regex, '')
```

...excuse my coffeescript ;-)

As a user of this repo, I'd probably not favor the extra cycles for parsing out comments on each pass, as in this pull request. Maybe it's better not to parse each and every element, notwithstanding that it also matters what is the treatment of comments elsewhere in the CSS input.

**Comment by jonathanong** [comment]
i'm +1 to that but people are inevitably going to complain. plus, i don't see performance an issue with this library.

**Comment by andreypopp** [comment]
Removing comments before parsing would break position information and so error reporting and source maps.

**Comment by BYK** [comment]
The correct regex for CSS comments is `/\/\*[^*]*\*+([^/*][^*]*\*+)*\//g` btw. This is from http://www.w3.org/TR/CSS21/grammar.html

**Comment by jonathanong** [comment]
hah. thank god for that regex! this PR's test was actually incorrect. thank god for not pulling it :)

**Comment by BYK** [comment]
@jonathanong is there a release planned that includes this change?

**Comment by jonathanong** [comment]
yeah v2

**Pull request closed without merging**
