### PR TITLE
Fixed bug when the parser stopped working met statement unnamed.

### PR DESCRIPTION
**Pull request by vladkens**
The CSS:

``` css
b { color: red; }
{ color: green; }
a {color: blue; }
```

earlier parsed to

``` js
{
    "type": "stylesheet",
    "stylesheet": {
        "rules": [
            {
                "type": "rule",
                "selectors": [
                    "b"
                ],
                "declarations": [
                    {
                        "type": "declaration",
                        "property": "color",
                        "value": "red"
                    }
                ]
            }
        ]
    }
}
```

now

``` js
{
    "type": "stylesheet",
    "stylesheet": {
        "rules": [
            {
                "type": "rule",
                "selectors": [
                    "b"
                ],
                "declarations": [
                    {
                        "type": "declaration",
                        "property": "color",
                        "value": "red"
                    }
                ]
            },
            {
                "type": "rule",
                "selectors": [],
                "declarations": [
                    {
                        "type": "declaration",
                        "property": "color",
                        "value": "green"
                    }
                ]
            },
            {
                "type": "rule",
                "selectors": [
                    "a"
                ],
                "declarations": [
                    {
                        "type": "declaration",
                        "property": "color",
                        "value": "blue"
                    }
                ]
            }
        ]
    }
}
```

### CODE REVIEW

**Comment by tj** [comment]
cool, test please!

**Comment by tj** [comment]
although we should maybe just output an error there

**Comment by vladkens** [comment]
Sometimes I see in CSS such constructions. Don't think this is really critical.

**Comment by vladkens** [comment]
But you decide. Maybe can and throw an exception.

**Comment by jonathanong** [comment]
personally i'd rather throw an exception. is that even valid CSS?

eitherway, you need a rebase and squash

**Comment by benschwarz** [comment]
Its invalid, an exception should be thrown.

**Pull request closed without merging**
