### PR TITLE
Compile atrules in advance

### PR DESCRIPTION
**Pull request by fb55**
Cache the regexp & avoid unnecessary wrapper methods

### CODE REVIEW

**Comment by jonathanong** [comment]
needs a rebase

**Comment by jonathanong** [comment]
@fb55 still interested? otherwise i'm going to close

**Comment by fb55** [comment]
I'm currently on vacation in Laos, without access to a computer (if you don't count my phone). Rebasing this should be trivial, but I'm unable to do so for at least two more weeks.

**Comment by jonathanong** [comment]
okay cool. as long as you've responded. don't like hanging PRs :)

**Comment by fb55** [comment]
And it's rebased.

**Comment by jonathanong** [comment]
woo ;D

**Pull request merged**
