### PR TITLE
Add case in test, when the comment is between selector. Add Simple solut...

### PR DESCRIPTION
**Pull request by fedyk**
It isn't an elegant implementation, but it's work

### CODE REVIEW

**Comment by jonathanong** [comment]
LGTM @visionmedia

**Comment by tj** [comment]
ugh haha who does that :(

**Comment by jonathanong** [comment]
@visionmedia anarchists

**Comment by tj** [comment]
going to close until we know that people actually do this, otherwise we're just chasing bugs that are irrelevant

**Comment by jonathanong** [comment]
Haha people are inevitably going to complain.

**Comment by brettstimmerman** [comment]
Strangely I ran into this issue today at work. It was unnecessary and we nuked those comments, but it can happen.

**Comment by michaelficarra** [comment]
Agreed. Definitely not an extraordinary case. [This](https://github.com/Constellation/escodegen/issues/128) is an extraordinary case that you'll never actually see.

**Comment by necolas** [comment]
Yeah, this is not uncommon. We had library code that does this (I think some jQuery UI stuff). So people definitely do it and the parser should be resilient in those situations.

**Comment by tj** [comment]
haha good old jquery ui..

**Comment by jonathanong** [comment]
just realized normalize.css has a comment between selectors, but before a `\n`: https://github.com/necolas/normalize.css/blob/dafaf9ee60ff76173954aca755c78a6912a0ee6c/normalize.css#L325. yet, autoprefixer does not fail. just thought that was interesting.

**Comment by necolas** [comment]
Intra-declaration was the problem for the parser that we hit:

```
.a {
   margin: 0 /* comment */;
}
```

**Comment by tj** [comment]
@necolas hmm weird that definitely shouldn't fail that's a bit of a different case

**Comment by tj** [comment]
oh I see it becomes part of the value

**Comment by jonathanong** [comment]
landed: https://github.com/visionmedia/css-parse/commit/ce56f466e3d2eb2791f86436af6fab9953ded48f

**Pull request closed without merging**
